### ISSUE TITLE
Connecting to MySQL database will not work when using sonarRunner

### ISSUE THREAD

**Issue by jugalps** [webdizz/docker-sonarqube-plugins#2]
If you are using sonarRunner from a `maven` or a `gradle` build, you need to specify the following property in your build file:
`sonar.jdbc.url=jdbc:mysql://${env:DB_PORT_3306_TCP_ADDR}`
However, if appropriate priviliges are not granted to the client machine from where the build is running you will run into [access denied error for the sonarqube user from this machine.](http://stackoverflow.com/questions/7247945/unable-to-access-sonar-mysql-database-caused-by-java-sql-sqlexception-access-d). 

Instead of using the standard MySQL image for the docker repository, you can use [this image](https://github.com/tpires/docker-sonar/tree/master/sonar-mysql), which will not have this issue.

**Comment by webdizz** [comment]
Well, I forget about exposing of port to remote in docker-compose.yml, made fix of this. Thanks for letting to know.
